"""first commit

Revision ID: cfd388fd8820
Revises: 
Create Date: 2025-01-22 22:09:28.595916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd388fd8820'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeding_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_1_id', sa.UUID(), nullable=False),
    sa.Column('parent_2_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('litter',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('breeding_event_id', sa.UUID(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['breeding_event_id'], ['breeding_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breeding_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('litter')
    op.drop_table('breeding_event')
    # ### end Alembic commands ###
